### PR TITLE
Fixing SonarLint Errors

### LINKED ISSUE #12: SonarLint Check
Check the whole project with the SonarLint scaning tool and examine the result, fixing the errors given by SonarLint. If it is not considered as an error than write a report why it is not an error

### PR DESCRIPTION
**Pull request by burkodigergely**
I ran SonarLint on the project and fixed the errors thrown by the program

### Checklist

- [x] An issue was first created **before** opening this pull request
- [x] The new code follows the [contribution guidelines](CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests to ensure that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: DataStructures/Dictionaries/CuckooHashTable.cs [hunk 1]
```diff
@@ -114,7 +114,7 @@ private void _rehash()
         /// </summary>
         private void _rehash(int newCapacity)
         {
-            int primeCapacity = PRIMES.GetNextPrime(newCapacity);
+            _ = PRIMES.GetNextPrime(newCapacity);
```
Comment (AkosUzonyi) [inline DataStructures/Dictionaries/CuckooHashTable.cs]: Maybe we could even remove that underline too

File: DataStructures/Dictionaries/CuckooHashTable.cs [hunk 2]
```diff
@@ -164,9 +164,9 @@ private int _cuckooHash(TKey key, int whichHashFunction)
         private bool _isActive(int index)
         {
             if (index < 0 || index > _collection.Length)
-                throw new IndexOutOfRangeException();
+                throw new ArgumentException($"Invalid argument");
```
Comment (AkosUzonyi) [inline DataStructures/Dictionaries/CuckooHashTable.cs]: I'm not sure that ArgumentException is beter than IndexOutOfRangeException here.

File: DataStructures/Graphs/UndirectedWeightedDenseGraph.cs [hunk 3]
```diff
@@ -109,10 +109,10 @@ public virtual IEnumerable<WeightedEdge<T>> Edges
         /// <summary>
         ///     Get all incoming edges to a vertex
         /// </summary>
-        public virtual IEnumerable<WeightedEdge<T>> IncomingEdges(T vertex)
+        public new virtual IEnumerable<WeightedEdge<T>> IncomingEdges(T vertex)
         {
             if (!HasVertex(vertex))
-                throw new ArgumentOutOfRangeException("One of vertex is not part of the graph.");
+                throw new ArgumentOutOfRangeException($"One of vertex is not part of the graph.");
```
Comment (AkosUzonyi) [inline DataStructures/Graphs/UndirectedWeightedDenseGraph.cs]: I think we shouldn't add a "$" before strings if we don't use string interpolation.
But it would be a good idea to use interpolation for printing the vertex.

File: DataStructures/Hashing/PrimeHashingFamily.cs [hunk 4]
```diff
@@ -68,11 +68,11 @@ public void GenerateNewFunctions()
         public int Hash(int preHashedKey, int whichHashFunction)
         {
             if (whichHashFunction <= 0 || whichHashFunction > _numberOfHashFunctions)
-                throw new ArgumentOutOfRangeException("WhichHashFunction parameter should be greater than zero or equal to the number of Hash Functions.");
+                throw new ArgumentOutOfRangeException($"WhichHashFunction parameter should be greater than zero or equal to the number of Hash Functions.");
 
             int preHashValue = 0;
             int multiplier = _multipliersVector[whichHashFunction - 1];
-            var characters = preHashedKey.ToString().ToCharArray();
+            _ = preHashedKey.ToString().ToCharArray();
```
Comment (AkosUzonyi) [inline DataStructures/Hashing/PrimeHashingFamily.cs]: I think this line could be removed entirely

File: DataStructures/Heaps/BinomialMinHeap.cs [hunk 5]
```diff
@@ -113,6 +116,13 @@ private void _removeAtIndex(int minIndex)
             --_size;
         }
 
+        private void CheckCapacity(int capacity)
+        {
+            string message = $"Capacity is negative: {capacity}";
+            if (capacity <= 0)
+                throw new ArgumentOutOfRangeException(message);
```
Comment (AkosUzonyi) [inline DataStructures/Heaps/BinomialMinHeap.cs]: This message variable could be inlined in the exception constructor.

**Review by AkosUzonyi — CHANGES_REQUESTED** [review]
Nice :)

Please also add a new markdown documentation file about static analysis (eg. `doc/static_analysis.md`) containing a short description of these changes.

File: DataStructures/Dictionaries/CuckooHashTable.cs (hunk 1 above)
Comment (AkosUzonyi) [reply DataStructures/Dictionaries/CuckooHashTable.cs]: Looking more closely at this, looks like this line and the PRIMES field can be removed, they are not used at all.

File: DataStructures/Graphs/UndirectedWeightedDenseGraph.cs (hunk 3 above)
Comment (AkosUzonyi) [reply DataStructures/Graphs/UndirectedWeightedDenseGraph.cs]: So I suggest to print the actual vertex here with interpolation.

And in the other places where "$" is inserted, either use interpolation actually, or if there is no variable to print, just remove the "$" sign.

**Comment by AkosUzonyi** [comment]
I really look forward to an update on this pull request.

File: DataStructures/Heaps/BinomialMinHeap.cs [hunk 6]
```diff
@@ -182,13 +192,14 @@ public bool IsEmpty
...
 
+
         /// <summary>
         /// Initializes this heap with a collection of elements.
         /// </summary>
         public void Initialize(IList<T> newCollection)
         {
             if (newCollection == null)
-                throw new ArgumentNullException();
+                throw new ArgumentNullException($"The provided parameter was null");
```
Comment (MarcellHarmaci) [inline DataStructures/Heaps/BinomialMinHeap.cs:201]: Why are we using parameterizable strings when there are no parameters?
This question also applies to the other exception messages without parameters.

Comment (gyupetosz) [reply DataStructures/Heaps/BinomialMinHeap.cs:201]: SonarLint suggested to extend the exception descreption so we made it open for future clarifications by added variables.

Comment (AkosUzonyi) [reply DataStructures/Heaps/BinomialMinHeap.cs:201]: I agree with @MarcellHarmaci, the "$" sign is unnecessary here.

The added message could be useful, but then the parameter name should be included.
